name: ifeomachukwuka
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+4

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # introduction_screen: ^3.1.12
  shared_preferences: ^2.0.11
  cupertino_icons: ^1.0.2
  webview_flutter: ^3.0.4
  provider: ^6.0.5
  fluttertoast: ^8.2.4
  url_launcher: ^6.0.10
  carousel_slider: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#2a285a"
  image: assets/new/logo1_black.png
  image_dark: assets/new/logo2_white.png
  color_dark: "#000000"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app_icon.png"

flutter:
  assets:
    - assets/
    - assets/logo/
    - assets/products/
    - assets/banner/
    - assets/intro/
    - assets/logo/white.png
  uses-material-design: true
  fonts:
    - family: Satoshi
      fonts:
        - asset: font/Satoshi/Satoshi-Regular.otf

    - family: Nunito
      fonts:
        - asset: font/Nunito/Nunito-Regular.ttf
